front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    # - mongo:mongo
    - memcached:memcached
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - /Users/Shin/Dropbox/500.Programing/php-dockerized/www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

# mongo:
#   image: mongo
#   ports:
#     - "27017:27017"

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
